# Practical - 3 : Write a NumPy program to implement following operation

### • to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order

In [1]:
# Name : Dharmik M Kukadiya 
#Enrollment : 216270307003

import numpy as np

x = np.arange(1, 15)
print("Original array:",x)

print("After splitting:")

print(np.split(x, [2, 6]))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


### • to stack arrays horizontally (column wise)

In [2]:
# Name : Dharmik M Kukadiya 
#Enrollment : 216270307003

import numpy as np

i = np.array([ 1, 2, 3] )
print ("1st Input array : \n", i)

in2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in2)

out = np.hstack((i, in2))
print ("Output horizontally stacked array:\n ", out)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]
