# Practical 2 : Write a NumPy program to implement following operation

### • to convert a list of numeric values into a one-dimensional NumPy array

In [1]:
# Name : Dharmik M Kukadiya 
#Enrollment : 216270307003

import numpy

l = [1, 7, 0, 6, 2, 5, 6]

a = numpy.array(l)

print ("List: ", l)

print ("Array: ", a)

List:  [1, 7, 0, 6, 2, 5, 6]
Array:  [1 7 0 6 2 5 6]


### • to create a 3x3 matrix with values ranging from 2 to 10

In [2]:
# Name : Dharmik M Kukadiya 
# Enrollment : 216270307003

import numpy as np

a = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10])

n = a.reshape(3, 3)

print(n)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### • to append values at the end of an array

In [3]:
# Name : Dharmik M Kukadiya 
#Enrollment : 216270307003

import numpy as np

x = [10, 20, 30]

print("Original array:")
print(x)

x = np.append(x, [40])
print("After append values to the end of the array:")

print(x)


Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40]


### • to create another shape from an array without changing its data (3*2 to 2*3) 

In [4]:
# Name : Dharmik M Kukadiya 
#Enrollment : 216270307003

import numpy as np

x = np.array([1, 2, 3, 4, 5, 6])

y = np.reshape(x,(3,2))

print("Reshape 3x2:")
print(y)

z = np.reshape(x,(2,3))
print("Reshape 2x3:")

print(z)


Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]
